### PR TITLE
[IT] Initial translation

### PR DESCRIPTION
**Pull request by toyr99**
Still have some work to do. Will finish later.

### CODE REVIEW

**Comment by zephiK** [comment]
When it's complete, I'll accept the pull request. It most likely won't make it for the next build unless you can be finished with the translations in less than a hour (or so).

**Comment by toyr99** [comment]
no problem, go ahead

**Comment by zephiK** [comment]
Keep working on them :) next build probably won't be until another week or whenever I have something to release.

**Comment by toyr99** [comment]
working right now actually. some time ago i also wrote a tutorial on xda cause i used to translate mahdi, i guess it might be useful for others who want to translate too. anyway, good you have a week or so, i'll have time to translate other packages too then. thanks :)

**Comment by zephiK** [comment]
No worries ;) If I release early I'll just include whatever you have completed. Thanks for the translations as you continue working on them.

**Comment by walker93** [comment]
I just gave a fast look at the translations and they are perfect!
Thanks toyr99 for translate into italian :) 
I hope to see them in the rom soon

**Comment by toyr99** [comment]
Love the rom and thought it deserved this. ;)

**Pull request closed without merging**
