### PR TITLE
Make QS background themeable (1/2)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zephiK** [comment]
I don't understand why you're making a commit to make QS background themeable.
Which layer themes utilizes this? Provide a detailed description or I'm not including this.

**Comment by ghost** [comment]
That's the only screen in Settings with the hardcoded background color so cannot be changed eg theme with dark background in settings will still have this background gray. Exposed for theming so background color can be changed to match the rest of the theme.

**Comment by zephiK** [comment]
As I mentioned in my first comment,
Which layer themes utilizes this?

I know what the code is doing and what you're trying to accomplish it but who uses this style of layering?

**Comment by ghost** [comment]
Oh, sorry. My theme will be using this, it's called MIUI 6. Probably other themes will appreciate it as well. 
I couldn't find the other way to theme this screen.

**Comment by zephiK** [comment]
Merged a larger commit that does the same thing you're doing,
https://github.com/zephiK/android_packages_apps_Settings/commit/4450a81cab0988897ceef2609f95711a68de9c34

**Pull request closed without merging**
